### ISSUE TITLE
[Error] AttributeError: 'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by s7x** [intrudir/BypassFuzzer#2]
Hello there,

First of all, awesome tool you have there, thanks for this gem.
There's an **AttributeError** error when running the tool (sometimes, not on every website tested):

**Command used**:

```
bypassfuzzer -u 'http://10.3.5.14/simplesaml/admin/phpinfo.php' -sh
```

**Stack Trace**:

```
Response Code: 404	Length: 307	Payload: 10.3.5.14/..%09simplesaml..%09/admin/phpinfo.php
Response Code: 404	Length: 304	Payload: 10.3.5.14/..%09simplesaml/admin/phpinfo.php
Path payload causing a hang-up: http://10.3.5.14/..%0d/;simplesaml..%0d/;/admin/phpinfo.php
Error I get: 
	('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Retrying...
Path payload causing a hang-up: http://10.3.5.14/..%0d/;simplesaml..%0d/;/admin/phpinfo.php
Error I get: 
	('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Retrying...
Path payload causing a hang-up: http://10.3.5.14/..%0d/;simplesaml..%0d/;/admin/phpinfo.php
Error I get: 
	('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Retrying...
Path payload causing a hang-up: http://10.3.5.14/..%0d/;simplesaml..%0d/;/admin/phpinfo.php
Error I get: 
	('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Retrying...
Retried 3 times.
Traceback (most recent call last):
  File "/usr/share/bypassfuzzer/bypassfuzzer.py", line 180, in <module>
    Fuzzer.path_attack(req_method, http_vers, headers, body_data, cookies)
  File "/usr/share/bypassfuzzer/core/fuzzer/fuzzer.py", line 123, in path_attack
    resp_path = response.url.split('/',2)[-1]
                ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'url'
```

![image](https://github.com/intrudir/BypassFuzzer/assets/33422344/290a589e-fb3a-4a7f-87f0-ebcaf48b44f3)

Cheers!

**Comment by doublesecc** [comment]
I get this same error after the tool retries a path payload that causes a hang-up:
```python
Path payload causing a hang-up: https://[REDACTED]/%09%3blogs
Error I get:
        ('Connection aborted.', HTTPException('got more than 100 headers'))
Retrying...
Path payload causing a hang-up: https://[REDACTED]/%09%3blogs
Error I get:
        ('Connection aborted.', HTTPException('got more than 100 headers'))
Retrying...
Path payload causing a hang-up: https://[REDACTED]/%09%3blogs
Error I get:
        ('Connection aborted.', HTTPException('got more than 100 headers'))
Retrying...
Path payload causing a hang-up: https://[REDACTED]/%09%3blogs
Error I get:
        ('Connection aborted.', HTTPException('got more than 100 headers'))
Retrying...
Retried 3 times.
Traceback (most recent call last):
  File "/opt/github/BypassFuzzer/bypassfuzzer.py", line 178, in <module>
    Fuzzer.path_attack(req_method, http_vers, headers, body_data, cookies)
  File "/opt/github/BypassFuzzer/core/fuzzer/fuzzer.py", line 135, in path_attack
    resp_path = response.url.split('/',2)[-1]
AttributeError: 'NoneType' object has no attribute 'url'
```

**Comment by intrudir** [comment]
@s7x @doublesecc  Thank you for the feedback and opening the issue! I believe this should be fixed now. the tool should (correctly) retry 3 times and move on to the next payload.
